# Generated by Django 5.1.6 on 2025-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_project_applyproject_projectevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='backend.specialty', verbose_name='Profil recherché'),
        ),
    ]
