# Generated by Django 5.1.6 on 2025-02-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_project_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='specialty',
            field=models.ManyToManyField(blank=True, null=True, to='backend.specialty', verbose_name='Profil recherché'),
        ),
    ]
