# Generated by Django 5.1.6 on 2025-03-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_project_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount',
            field=models.FloatField(default=1000, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date de début'),
        ),
    ]
