# Generated by Django 5.1.6 on 2025-03-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_project_amount_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='adress',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresse'),
        ),
    ]
