# Generated by Django 5.1.6 on 2025-03-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_project_adress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='start_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='applyproject',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='applyproject',
            name='amount',
            field=models.FloatField(default=1000, verbose_name='Montant'),
        ),
        migrations.AddField(
            model_name='applyproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='applyproject',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Durée'),
        ),
    ]
