# Generated by Django 5.1.6 on 2025-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
