# Generated by Django 5.1.6 on 2025-02-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_district_user_address_user_birthplace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quater',
            name='district',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_quater',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Quater',
        ),
    ]
