# Generated by Django 5.1.6 on 2025-02-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_district_quater_user_user_quater'),
        ('backend', '0005_alter_project_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='competence',
            field=models.ManyToManyField(blank=True, to='backend.specialty', verbose_name='Competence'),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.ManyToManyField(blank=True, to='backend.job', verbose_name='Profession'),
        ),
    ]
